question_data = [
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Video Games",
        "question": "Doki Doki Literature Club was developed in Japan.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Entertainment: Video Games",
        "question": "In the Season One Championship of &quot;League of Legends&quot;, the highest achievable rank was Diamond.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Science &amp; Nature",
        "question": "Anatomy considers the forms of macroscopic structures such as organs and organ systems.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Film",
        "question": "Ewan McGregor did not know the name of the second prequel film of Star Wars during and after filming.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "General Knowledge",
        "question": "Coca-Cola&#039;s original colour was green.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Entertainment: Video Games",
        "question": "In &quot;Super Mario World&quot;, the rhino mini-boss, Reznor, is named after the lead singer of the band &quot;Nine Inch Nails&quot;.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Entertainment: Video Games",
        "question": "In &quot;League of Legends&quot;, there exists four different types of Dragon.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Science &amp; Nature",
        "question": "Type 1 diabetes is a result of the liver working improperly.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Entertainment: Video Games",
        "question": "Minecraft wasn&rsquo;t the original name to Minecraft.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Animals",
        "question": "In 2016, the IUCN reclassified the status of Giant Pandas from endangered to vulnerable.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Video Games",
        "question": "In &quot;Super Mario 3D World&quot;, the Double Cherry power-up originated from a developer accidentally making two characters controllable.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "hard",
        "category": "Entertainment: Japanese Anime &amp; Manga",
        "question": "Kiznaiver is an adaptation of a manga.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "General Knowledge",
        "question": "Kissing someone for one minute burns about 2 calories.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "History",
        "question": "Kublai Khan is the grandchild of Genghis Khan?",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Animals",
        "question": "The average lifespan of a wildcat is only around 5-6 years. ",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Music",
        "question": "Korean girl group, TWICE, consists of 9 members",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Japanese Anime &amp; Manga",
        "question": "Gosho Aoyama Made This Series: (Detective Conan \/ Case Closed!)",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Science &amp; Nature",
        "question": "Salt is 100% composed of Sodium.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Film",
        "question": "The film &quot;2001: A Space Odyssey&quot; was released on December 31st, 2000.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Geography",
        "question": "Seoul is the capital of North Korea.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "hard",
        "category": "Science &amp; Nature",
        "question": "It was once believed that injecting shark cartilage into people would prevent them from contracting cancer.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Television",
        "question": "Klingons express emotion in art through opera and poetry.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Japanese Anime &amp; Manga",
        "question": "In the 1988 film &quot;Akira&quot;, Tetsuo ends up destroying Tokyo.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Geography",
        "question": "New Haven is the capital city of the state of Connecticut in the United States.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Entertainment: Film",
        "question": "Sean Connery wasn&#039;t in &quot;Indiana Jones and the Kingdom of the Crystal Skull&quot; because he found retirement too enjoyable.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Sports",
        "question": "Peyton Manning retired after winning Super Bowl XLIX.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Politics",
        "question": "Russia passed a law in 2013 which outlaws telling children that homosexuals exist.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Film",
        "question": "Shaquille O&#039;Neal appeared in the 1997 film &quot;Space Jam&quot;.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "General Knowledge",
        "question": "It is automatically considered entrapment in the United States if the police sell you illegal substances without revealing themselves.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Geography",
        "question": "Alaska is the largest state in the United States.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "hard",
        "category": "Entertainment: Video Games",
        "question": "The first &quot;Metal Gear&quot; game was released for the PlayStation 1.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Geography",
        "question": "The surface area of Russia is slightly larger than that of the dwarf planet Pluto.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Books",
        "question": "&quot;Elementary, my dear Watson&quot; is a phrase that is never truly said within the Conan Doyle books of Sherlock Holmes.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Film",
        "question": "In the original Star Wars trilogy, Alec Guinness provided the voice for Darth Vader.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Video Games",
        "question": "The end credits sequence in Grand Theft Auto 5 is over half an hour long.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "History",
        "question": "Abraham Lincoln was the first U.S. President to be born outside the borders of the thirteen original states. ",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "History",
        "question": "Former United States Presidents John Adams and Thomas Jefferson died within hours of each other.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "General Knowledge",
        "question": "SCP-173 was the first SCP article written for the web-based collaborative fiction project known as the &quot;SCP Foundation&quot;",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Video Games",
        "question": "In Team Fortress 2, being disguised as a scout or medic results in a speed boost.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Japanese Anime &amp; Manga",
        "question": "In the &quot;Melancholy of Haruhi Suzumiya&quot; series, the narrator goes by the nickname Kyon.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "General Knowledge",
        "question": "There are 86400 seconds in a day.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Geography",
        "question": "California is larger than Japan.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Video Games",
        "question": "In Terraria, you can craft the Cell Phone pre-hardmode.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "hard",
        "category": "Politics",
        "question": "Joko Widodo has appeared in the cover of a TIME magazine.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Entertainment: Video Games",
        "question": "Metal Gear Solid V: The Phantom Pain runs on the Fox Engine.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "History",
        "question": "Assyrian king Sennacherib&#039;s destruction of Babylon in 689 BCE was viewed as a triumph by other Assyrian citizens.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Film",
        "question": "George Lucas directed the entire original Star Wars trilogy.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Entertainment: Video Games",
        "question": "In World of Warcraft lore, Thrall is the original wielder of &quot;Doomhammer&quot;.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Geography",
        "question": "There is an island in Japan called \u014ckunoshima, A.K.A. &quot;Rabbit Island&quot;, so named because of it&#039;s huge population of rabbits.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Entertainment: Video Games",
        "question": "The scrapped Sonic the Hedgehog 2 level &quot;Hidden Palace Zone&quot; was later reused in the iOS port of the game. ",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
]
